# Generated by Django 4.0.4 on 2022-05-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
