# Generated by Django 4.0.4 on 2022-05-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorvendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
