# Generated by Django 4.0.4 on 2022-05-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('users', '0002_customerorvendor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorvendor',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='addresses.address'),
        ),
    ]
