# Generated by Django 4.0.4 on 2022-05-10 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0003_orderdetails_total_amount'),
        ('products', '0002_initial'),
        ('order_items', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='price',
            new_name='price_per_unit',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsList', to='order_details.orderdetails'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
