# Generated by Django 4.0.4 on 2022-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0004_orderitems_order_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
