# Generated by Django 4.0.4 on 2022-04-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0007_remove_products_category_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='categories.categories'),
        ),
    ]
